[package]
name = "casper-liquid-staking"
version = "0.1.0"
edition = "2021"

[dependencies]
casper-contract = "1.4.4"
casper-types = "1.5.0"

[features]
default = ["std"]
std = [
    "casper-contract/std",
    "casper-types/std",
]
